---
- name: Rebootar AP Intelbras via expect
  hosts: all
  gather_facts: no

  tasks:
    - name: Reboot usando expect
      ansible.builtin.expect:
        command: ssh admin@{{ inventory_hostname }}
        responses:
          'password:': "{{ ansible_password }}"
          '.*#': "reboot"
        timeout: 30
      vars:
        ansible_connection: local
      ignore_errors: false
      failed_when: false
