---
- name: Rebootar Bridge Ruckus
  hosts: all
  gather_facts: no
  vars:
    ansible_ssh_common_args: >
      -o KexAlgorithms=+diffie-hellman-group1-sha1 
      -o HostKeyAlgorithms=+ssh-rsa 
      -o PubkeyAcceptedKeyTypes=+ssh-rsa 
      -o StrictHostKeyChecking=no 
      -o UserKnownHostsFile=/dev/null

  tasks:
    - name: Reboot usando expect
      ansible.builtin.expect:
        command: ssh {{ ansible_user }}@{{ inventory_hostname }}
        responses:
          'Please login:': "{{ ansible_user }}"
          'password :': "{{ ansible_password }}"
          'rkscli:': 'reboot'
        timeout: 10
        echo: yes
        strip_prompt: false
      vars:
        ansible_connection: local
      ignore_errors: true
      failed_when: false
