- name: Reboot Ruckus
  hosts: all
  gather_facts: no
  
  tasks:
    - name: Reboot via shell com expect
      ansible.builtin.expect:
        command: ssh -o StrictHostKeyChecking=no {{ inventory_hostname }}
        responses:
          'login:': "{{ ansible_user }}"
          'password:': "{{ ansible_password }}"
          '\# ': 'reboot'
        timeout: 10
        echo: yes
      register: result
      ignore_errors: yes
