- name: Reboot Ruckus via expect
  hosts: all
  gather_facts: no
  vars:
    ansible_ssh_common_args: >
      -o StrictHostKeyChecking=no
      -o UserKnownHostsFile=/dev/null
  tasks:
    - name: Reboot via shell com expect
      ansible.builtin.expect:
        command: ssh -o StrictHostKeyChecking=no {{ inventory_hostname }}
        responses:
          'login:': "{{ ansible_user }}"
          'password:': "{{ ansible_password }}"
          '\# ': 'reboot'
        timeout: 10
        echo: yes
      register: result
      ignore_errors: yes

    - debug:
        var: result.stdout_lines
