---
- name: Rebootar AP Intelbras via expect
  hosts: all
  gather_facts: no

  tasks:
    - name: Reboot usando expect
      ansible.builtin.expect:
        command: /usr/bin/ssh admin@{{ inventory_hostname }}
        responses:
          'password:': "{{ ansible_password }}"
          '#\s*$': "reboot\n"
        timeout: 30
