---
- name: Rebootar Bridge Ruckus
  hosts: all
  gather_facts: no

  tasks:
    - name: Reboot usando expect
      ansible.builtin.expect:
        command: ssh {{ ansible_user }}@{{ inventory_hostname }}
        responses:
          'password:': "{{ ansible_password }}"
          '.*#': "reboot"
        timeout: 10
      vars:
        ansible_connection: local
      ignore_errors: true
      failed_when: false
