- name: Reboot Bridge Intelbras
  hosts: all
  gather_facts: no
  
 tasks:

    - name: Reboot via raw
      raw: reboot
      register: reboot_result
      ignore_errors: yes

    - name: Mostrar resultado do reboot
      debug:
        var: reboot_result
