- name: Reboot Bridge Intelbras
  hosts: all
  gather_facts: no
  vars:
    ansible_user: "{{ ansible_user }}"
    ansible_password: "{{ ansible_password }}"
    ansible_ssh_common_args: >
      -o StrictHostKeyChecking=no
      -o UserKnownHostsFile=/dev/null
      -o HostKeyAlgorithms=+ssh-rsa
      -o PubkeyAcceptedKeyTypes=+ssh-rsa
      -o KexAlgorithms=+diffie-hellman-group14-sha1
  tasks:
    - name: Reboot usando comando raw
      raw: reboot
      register: reboot_result
      ignore_errors: yes

    - name: Verificar resultado
      debug:
        msg: >
          {% if reboot_result.rc == 0 %}
            Reboot enviado com sucesso para {{ inventory_hostname }}
          {% else %}
            Falha ao tentar reiniciar {{ inventory_hostname }}. Detalhes: {{ reboot_result }}
          {% endif %}
