---
- name: Reboot Bridge Intelbras
  hosts: all
  gather_facts: no
  vars:
    ansible_ssh_common_args: >
      -o KexAlgorithms=+diffie-hellman-group1-sha1
      -o HostKeyAlgorithms=+ssh-rsa
      -o PubkeyAcceptedKeyTypes=+ssh-rsa
      -o StrictHostKeyChecking=no
      -o UserKnownHostsFile=/dev/null

  tasks:
    - name: Reboot via sshpass
      shell: |
        sshpass -p '{{ ansible_password }}' ssh \
          -o KexAlgorithms=+diffie-hellman-group1-sha1 \
          -o HostKeyAlgorithms=+ssh-rsa \
          -o PubkeyAcceptedKeyTypes=+ssh-rsa \
          -o StrictHostKeyChecking=no \
          -o UserKnownHostsFile=/dev/null \
          {{ ansible_user }}@{{ inventory_hostname }} 'reboot'
      args:
        warn: false
      register: reboot_result
      failed_when: false

    - name: Mostrar resultado
      debug:
        var: reboot_result.stdout_lines
