- name: Reboot Ruckus via expect
  hosts: all
  gather_facts: no
  vars:
    ansible_ssh_common_args: >
      -o KexAlgorithms=+diffie-hellman-group1-sha1 
      -o HostKeyAlgorithms=+ssh-rsa 
      -o PubkeyAcceptedKeyTypes=+ssh-rsa 
      -o StrictHostKeyChecking=no 
      -o UserKnownHostsFile=/dev/null
  tasks:
    - name: Reboot via shell com expect
      ansible.builtin.expect:
        command: ssh -tt {{ inventory_hostname }}
        responses:
          'Please login:': "{{ ansible_user }}"
          'password :': "{{ ansible_password }}"
          'rkscli:': 'reboot'
        timeout: 30
        echo: yes
        strip_prompt: false
      register: result
      ignore_errors: yes

    - debug:
        var: result.stdout_lines
