
---
- name: Reiniciar APs
  hosts: all
  gather_facts: no
  become: no

  tasks:
    - name: Rebootar AP
      ansible.builtin.raw: "sleep 2 && reboot"
      async: 1
      poll: 0
      ignore_errors: true
