- name: Reboot Bridges Intelbras via raw
  hosts: all
  gather_facts: no
  vars:
    ansible_ssh_common_args: >-
      -o KexAlgorithms=+diffie-hellman-group1-sha1
      -o HostKeyAlgorithms=+ssh-rsa
  tasks:
    - name: Reboot via raw
      raw: reboot
      ignore_errors: yes
      register: reboot_result

    - name: Mostrar resultado do reboot
      debug:
        var: reboot_result
