---
- name: Atualizar servidores Ubuntu
  hosts: all
  sudo: yes
  become: yes
  gather_facts: yes

  tasks:
    - name: Atualizar lista de pacotes
      apt:
        update_cache: yes

    - name: Atualizar todos os pacotes
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes
