- name: Atualizar RouterOS usando repositório interno (via SSH)
  hosts: all
  gather_facts: no
  connection: ssh
  vars:
    update_channel: "stable"
    wait_after_reboot: 120

  tasks:
    - name: (Opcional) Definir canal de atualização
      ansible.builtin.raw: /system package update set channel={{ update_channel }}

    - name: Verificar pacotes disponíveis e registrar saída
      ansible.builtin.raw: /system package update print
      register: update_status

    - name: Exibir status da atualização (para depuração)
      ansible.builtin.debug:
        var: update_status.stdout_lines

    - name: Baixar atualização
      ansible.builtin.raw: /system package update download
      when: "'New version available' in update_status.stdout" # Condição para baixar

    - name: Instalar atualização
      ansible.builtin.raw: /system package update install
      when: "'New version available' in update_status.stdout" # Condição para instalar

    - name: Aguardar router reiniciar e SSH voltar
      ansible.builtin.wait_for:
        host: "{{ ansible_host }}"
        port: "{{ ansible_port }}"
        delay: 10
        timeout: "{{ wait_after_reboot }}"
        state: started
      when: "'New version available' in update_status.stdout" # Aguarda reinício apenas se houve atualização

    - name: Verificar versão após reboot
      ansible.builtin.raw: /system resource print
