---
- name: Atualizar pacotes no Proxmox com dist-upgrade
  hosts: all
  become: yes  # Executar com privilégios de superusuário

  tasks:
    - name: Atualizar pacotes com dist-upgrade
      apt:
        update_cache: yes  # Atualizar cache dos pacotes
        upgrade: dist       # Realizar atualização com dist-upgrade
