---
- name: Atualizar servidores Ubuntu
  hosts: all
  become: yes
  become_user: ansible
  become_method: sudo
  gather_facts: yes

  tasks:

    - name: Atualizar todos os pacotes
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes
        allow_unauthenticated: yes
        force_apt_get: yes
        install_recommends: yes   
        
