---
- name: Atualizar servidores Ubuntu
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Atualizar todos os pacotes
      apt:
        update_cache: yes  # Atualizar cache dos pacotes
        upgrade: dist
        autoremove: yes
        autoclean: yes
        allow_unauthenticated: yes
        force_apt_get: yes
        install_recommends: yes   

    - name: Verifica se é necessario reiniciar
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file
     
    - name: Reinicia se for necessario
      reboot:
      when: reboot_required_file.stat.exists == true and reboot_required_file.stat.isreg == true
