---
- name: Atualizar pacotes no Proxmox 
  hosts: all
  become: yes  # Executar com privilégios de superusuário

  tasks:
    - name: Atualizar lista de pacotes
      apt:
         update_cache: yes  # Atualizar cache dos pacotes
        
    - name: Atualizar pacotes 
      command: apt-get dist-upgrade -y --ignore-missing
        
