---
- name: Atualizar pacotes no Proxmox com dist-upgrade
  hosts: all
  become: yes  # Executar com privilégios de superusuário

  tasks:
    - name: Atualizar pacotes com dist-upgrade
      apt:
        update_cache: yes  # Atualizar cache dos pacotes
        upgrade: yes 
        #autoremove: yes
        autoclean: yes
        allow_unauthenticated: yes
        force_apt_get: yes
        #install_recommends: yes
