- name: Atualizar RouterOS usando repositório interno (via SSH)
  hosts: all
  gather_facts: no
  connection: ssh
  vars:
    update_channel: "stable"
    wait_after_reboot: 120

  tasks:
    - name: (Opcional) Definir canal de atualização
      ansible.builtin.raw: /system package update set channel={{ update_channel }}

    - name: Verificar pacotes disponíveis e registrar saída
      ansible.builtin.raw: /system package update print
      register: update_status
      failed_when: false  # <- NÃO falhar se o comando retornar código de saída inesperado
      changed_when: false # <- NÃO marcar como "changed", pois é só leitura

    - name: Exibir status da atualização (para depuração)
      ansible.builtin.debug:
        var: update_status.stdout_lines

    - name: Baixar atualização
      ansible.builtin.raw: /system package update download
      when: "'New version is available' in update_status.stdout"
      # Dica: cheque exatamente o texto que aparece no seu RouterOS

    - name: Instalar atualização
      ansible.builtin.raw: /system package update install
      when: "'New version is available' in update_status.stdout"

    - name: Aguardar router reiniciar e SSH voltar
      ansible.builtin.wait_for:
        host: "{{ ansible_host }}"
        port: "{{ ansible_port }}"
        delay: 10
        timeout: "{{ wait_after_reboot }}"
        state: started
      when: "'New version is available' in update_status.stdout"

    - name: Verificar versão após reboot
      ansible.builtin.raw: /system resource print
