---
- name: Atualizar RouterOS via network_cli
  hosts: all
  gather_facts: no
  check_mode: no

  tasks:
    - name: Verificar pacotes disponíveis
      ansible.netcommon.cli_command:
        command: /system package update print
      register: update_status

    - name: Debug mostrar status da atualização
      debug:
        var: update_status.stdout

    - name: Baixar atualização (se disponível)
      ansible.netcommon.cli_command:
        command: /system package update download
      when: "'New version is available' in update_status.stdout"

    - name: Instalar atualização (se disponível)
      ansible.netcommon.cli_command:
        command: /system package update install
      when: "'New version is available' in update_status.stdout"

    - name: Esperar router reiniciar após instalação
      ansible.builtin.wait_for:
        host: "{{ inventory_hostname }}"
        port: "{{ ansible_port }}"
        delay: 10
        timeout: 120
        state: started
      when: "'New version is available' in update_status.stdout"

    - name: Verificar versão após reboot
      ansible.netcommon.cli_command:
        command: /system resource print
