- name: Atualizar RouterOS usando repositório interno (via SSH)
  hosts: all
  gather_facts: no
  connection: ssh
  vars:
    update_channel: "stable"
    wait_after_reboot: 120

  tasks:
    - name: (Opcional) Definir canal de atualização
      ansible.builtin.raw: /system package update set channel={{ update_channel }}

    - name: Verificar pacotes disponíveis
      ansible.builtin.raw: /system package update print

    - name: Baixar atualização
      ansible.builtin.raw: /system package update download

    - name: Instalar atualização
      ansible.builtin.raw: /system package update install

    - name: Aguardar router reiniciar e SSH voltar
      ansible.builtin.wait_for:
        host: "{{ ansible_host }}"
        port: "{{ ansible_port }}"
        delay: 10
        timeout: "{{ wait_after_reboot }}"
        state: started

    - name: Verificar versão após reboot
      ansible.builtin.raw: /system resource print
