---
- name: MikroTik RouterOS Upgrade via network_cli
  hosts: all
  gather_facts: no

  tasks:
    - name: (1) Verificar pacotes disponíveis
      ansible.netcommon.cli_command:
        command: /system package update print
      register: update_status

    - name: Debug saída
      debug:
        var: update_status.stdout

    - name: (2) Baixar atualização
      ansible.netcommon.cli_command:
        command: /system package update download
      when: "'New version is available' in update_status.stdout"

    - name: (3) Instalar atualização
      ansible.netcommon.cli_command:
        command: /system package update install
      when: "'New version is available' in update_status.stdout"

    - name: (4) Esperar router reiniciar
      ansible.builtin.wait_for:
        host: "{{ inventory_hostname }}"
        port: "{{ ansible_port }}"
        delay: 10
        timeout: 120
        state: started
      when: "'New version is available' in update_status.stdout"

    - name: (5) Verificar versão após reboot
      ansible.netcommon.cli_command:
        command: /system resource print
